server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: classpath:shared-config.yml
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/auth/$\{segment}
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/users/$\{segment}
        - id: role-service
          uri: http://role-service:8084
          predicates:
            - Path=/api/v1/roles/**
          filters:
            - RewritePath=/api/v1/roles/(?<segment>.*), /api/roles/$\{segment}
        - id: mail-service
          uri: http://mail-service:8085
          predicates:
            - Path=/api/v1/mail/**
          filters:
            - RewritePath=/api/v1/mail/(?<segment>.*), /api/mail/$\{segment}
        - id: template-service
          uri: http://template-service:8086
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - RewritePath=/api/v1/templates/(?<segment>.*), /api/templates/$\{segment}

# Logging configuration for Docker
logging:
  level:
    '[com.vertyll.projecta]': INFO
    '[org.springframework.cloud.gateway]': INFO
    '[org.springframework.security]': WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      access: read-only
    prometheus:
      access: read-only
