sonar.projectKey=veds-mail-service
sonar.projectName=veds mail-service
sonar.sources=domain/src/main,application/src/main,infrastructure/src/main
sonar.tests=domain/src/test,application/src/test,infrastructure/src/test
sonar.java.binaries=**/build/classes
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml
sonar.issue.ignore.multicriteria=dto,command,domainModel,beans,tests,repository,entity
sonar.issue.ignore.multicriteria.dto.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.dto.resourceKey=**/dto/*.kt
sonar.issue.ignore.multicriteria.command.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.command.resourceKey=**/command/*.kt
sonar.issue.ignore.multicriteria.domainModel.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.domainModel.resourceKey=**/domain/model/*.kt
sonar.issue.ignore.multicriteria.beans.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.beans.resourceKey=**/config/ApplicationBeansConfig.kt
sonar.issue.ignore.multicriteria.tests.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.tests.resourceKey=**/src/test/**/*.kt
sonar.issue.ignore.multicriteria.repository.ruleKey=kotlin:S6517
sonar.issue.ignore.multicriteria.repository.resourceKey=**/persistence/repository/*.kt
sonar.issue.ignore.multicriteria.entity.ruleKey=kotlin:S6524
sonar.issue.ignore.multicriteria.entity.resourceKey=**/persistence/entity/*.kt
sonar.cpd.exclusions=**/config/TranslationCatalogueConfig.kt
