sonar.projectKey=veds-shared-messaging-kafka
sonar.projectName=veds shared-messaging-kafka
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=**/build/classes
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml
sonar.issue.ignore.multicriteria=tests
sonar.issue.ignore.multicriteria.tests.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.tests.resourceKey=**/src/test/**/*.kt
